
[phases.setup]
nixPkgs = ["openjdk21", "maven"]

[phases.install]
cmds = ["mvn dependency:resolve"]

[phases.build]
cmds = ["mvn clean package -DskipTests"]

[start]
cmd = "java -jar target/*.jar --spring.profiles.active=prod"

[build.env]
NIXPACKS_JAVA_VERSION = "21"
NIXPACKS_MAVEN_VERSION = "3.9"

