# Base de données H2 pour Render
spring.datasource.url=jdbc:h2:mem:produitdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA - Important: Laissez Hibernate créer les tables
spring.jpa.hibernate.ddl-auto=update  # ou create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# Désactiver la console H2 en production
spring.h2.console.enabled=false

# Serveur
server.port=${PORT:8080}